### ISSUE TITLE
Edgar Axel Sandoval Hernández 

### ISSUE THREAD

**Issue by EdgarExa** [SistemasTecTlaxiaco/actividad-4-mapa-mental-EdgarExa#1]
[COMUNICACION ORAL Y ESCRITA AXEL_114654.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-EdgarExa/files/9608800/COMUNICACION.ORAL.Y.ESCRITA.AXEL_114654.pdf)
Mapa mental

**Comment by josealfredo79** [comment]
Calificación 17

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
